version: '3'

services:
  notebook:
    image: jupyter/tensorflow-notebook:tensorflow-2.13.0
    container_name: tcc-ifsp
    command: "start-notebook.sh --ServerApp.token='' --ServerApp.password=''"
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/home/jovyan/work